### ISSUE TITLE
how to change the height of canvas by defualt it is taking half the width of reactchart and how to change the fill color of the react chart line or other css.

### ISSUE THREAD

**Issue by nandinias** [javascriptiscoolpl/react-chart-line#1]

**Comment by dprojects** [comment]
See index.html file here https://github.com/javascriptiscoolpl/react-chart-line/blob/master/index.html or just try "react-chart-all" module to get access to all charts.js versions with options.

**Comment by javascriptiscoolpl** [comment]
See index.html file here https://github.com/javascriptiscoolpl/react-chart-line/blob/master/index.html or just try "react-chart-all" module (described here https://www.npmjs.com/package/react-chart-all) to get access to all charts.js versions with options. The react-chart-line is the simplest version of chart.
